### ISSUE TITLE
Inconsistent port config display

### ISSUE THREAD

**Issue by chrisidefix** [m0ppers/syncthing-bar#11]
I am not sure if this is a real problem with the current `syncthing` config, but the web GUI settings *internally* still shows port `8080` inside the **GUI listen address** instead of port 8084. Probably won't cause any problems, but I noticed it showing up, when looking through the REST api output.

**Comment by m0ppers** [comment]
Hmm this seems to be one of the strange artifacts of bundling syncthing ;) Will investigate but i guess that's just how it is for now :S

**Comment by canton7** [comment]
Yeah, this is a Syncthing display issue.

**Comment by m0ppers** [comment]
just as @canton7 said: not fixable here. maybe i find time to fix it in syncthing itself. should be doable
