### ISSUE TITLE
Add a possibility to pause/stop sync

### ISSUE THREAD

**Issue by ech1965** [m0ppers/syncthing-bar#12]
Hello,

I'm migrating from btync to syncthing to synching my photos collection and lightroom catalog between my computer!

This works very well so far. 

I'd like to have an easy way to pause syncing before opening lightroom and un pause it after lightroom closed

A UI menu in the action would be a perfect place !

**Comment by x0x01** [comment]
+1

**Comment by chrisidefix** [comment]
I assume the easiest way to implement this is to stop `syncthing` completely (terminate the process) and then restart it again on request.

What would actually be awesome, is a settings / configuration item that would allow to automatically halt `syncthing` when certain applications are running (e.g. lightroom, iPhoto, etc).

**Comment by chrisidefix** [comment]
I added a basic version to pause syncthing in pull-request #15 which should resolve this issue

**Comment by m0ppers** [comment]
code is merged and there will be a release soon (as soon as the oustanding issues are resolved :D)
