### ISSUE TITLE
Tray icon should become white when the menu drops down

### ISSUE THREAD

**Issue by jamesgecko** [m0ppers/syncthing-bar#13]
Minor detail, but possibly worth fixing.

This is what f.lux (and all the default OS X tray icons) do.
![screenshot 2015-05-13 18 19 07](https://cloud.githubusercontent.com/assets/44252/7622342/cc038538-f99c-11e4-97ce-849d94ec75cc.png)

Here is what syncthing-bar does.
![screenshot 2015-05-13 18 19 18](https://cloud.githubusercontent.com/assets/44252/7622347/d4ed5098-f99c-11e4-9945-259526e70abd.png)

Syncthing's icon does change when selected, but it gets darker not lighter. Also, the entire icon is changed, even the transparent part.

In dark menubar mode, it is appropriate to not change the icon when selected. Again, the default menu bar widgets behave the same way.
![screenshot 2015-05-13 18 23 37](https://cloud.githubusercontent.com/assets/44252/7622416/50d01934-f99d-11e4-9f15-49d0c137262b.png)

**Comment by chrisidefix** [comment]
If somebody is looking into this, I would like to add that the menu-bar icon on a secondary screen behaves a little strange: The icon becomes fully white on whichever monitor is currently in-active.

![inactive](https://cloud.githubusercontent.com/assets/382555/7864152/af691454-0560-11e5-9a1e-6cb4389c0f38.jpg)

Under Mavericks a monitor that currently does not have the focus renders the menu-bar more transparent. When this happens the syncthing-bar icon changes completely. I wonder if this is a transparency issue with the icon or if some property is not defined in the Xcode project?

If anyone could point me into the right direction, I would like to help fix this.

**Comment by chrisidefix** [comment]
I figures that this was simply a transparency issue in the icon used. I added a new icon just for the menu bar, which fixes these problems: pull request: #14

**Comment by chrisidefix** [comment]
PS: if you prefer the inverted version of the icon - I also have that available...

**Comment by m0ppers** [comment]
Thanks for the new icon @chrisidefix. New release has been published :D closing :D

**Comment by jamesgecko** [comment]
Pure awesome. Thanks y'all!
