### ISSUE TITLE
Add some settings to configure syncthing-bar.

### ISSUE THREAD

**Issue by chrisidefix** [m0ppers/syncthing-bar#16]
It could be useful to have a settings dialogue for `syncthing-bar` that allows a bit more personalization of the application (especially the menu-bar icon could be made configurable). I committed a pull-request #15 for your review and pleasure. It's nothing special, but if there are any configuration defaults you would like to add in a more configurable way - you could probably use this to start from. (I already included the port number for example, but it needs a little more work to have any influence on starting the actual `syncthing`.

**Comment by m0ppers** [comment]
Wow this is huge! Awesome :D i finally found some time to check it. looking good.

I have a few (usability) comments: What is the port thing doing. It implies i can set a port while it won't have any effect (yet?).

About System Monitor: Is it this thing here: https://itunes.apple.com/de/app/system-monitor/id423368786?mt=12 ? Or what exactly is required? 5 EUR for a psgrep :D I should really focus more on developing on the mac. Is it possible to detect if it is active/present and disable these settings? If it is that system monitor: i kind of have a problem to cross-advertise a paid app :S Not sure yet. Doing a simple psgrep should be doable.

About the icons: there are now 3 settings concerning the icon :O is it really a use case to configure it (i like slim uis ;) ). For me your latest icon made perfect sense. it seemlessly integrates with the other standard apple icons and looks as good when switching to the dark theme.

I merged anyway already (but didn't prepare a new release yet).

Thanks for your efforts!

**Comment by chrisidefix** [comment]
Sure, no worries - was fun for me to get a bit more into Swift as well.

Regarding the port thing - the way I understand it - there are two port numbers of interest:
1) The web-ui port: This is probably one that should be made more configurable, since people may already use the same port (8084) for something else or just want to set it themselves.
2) The syncthing listen port: I am not exactly sure if this should also be configured in the settings.

So, until it really works, maybe those UI elements could simply be disabled, to not confuse the users.

Regarding the "system monitoring": No, that paid app has nothing to do with my implementation and I would have a problem with pulling some requirement like that into this project, too. I am not using a commandline tool (like `psgrep`), because: it would introduce a new dependency, which we would depend on and/or we would have to do the parsing for. Instead, I am using this to get the running processes (https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSWorkspace_Class/index.html).
```Swift
let r_apps = NSWorkspace().runningApplications as! [NSRunningApplication]
[...]
let r_app_name: String = r_app.localizedName!
```

Regarding the icons. Yes, minimal UI is good and this was more of a "let's see what we can do with this" exercise. I would probably retain the option to display a color icon, but the inverted version could go away.

**Comment by m0ppers** [comment]
i just created a release. there is still a "0" in front of it ;) So yeah "let's see what we can do with this"
