### ISSUE TITLE
Feature Request: Add the possibility to Pause while on Battery/Wifi

### ISSUE THREAD

**Issue by tintamarre** [m0ppers/syncthing-bar#19]
Il would be great to add the possibility to `Pause`/`Stop` Syncthing while the computer is on Battery and/or connected through Wifi (like the android App).

Syncthing drains battery a lot and I close it when my MacBook is on Battery. It would be great if it could be automated.

**Comment by m0ppers** [comment]
That sounds like a very useful addition. Hope to find time soon!
