### ISSUE TITLE
Caveats - There is one missing on the list

### ISSUE THREAD

**Issue by eject-it** [m0ppers/syncthing-bar#20]
It will Install a System Launch Agent causing syncthing to run as root and thereby making root the owner of newly downloaded files.

Well I could have checked the code and see what it does first, I guess.

**Comment by m0ppers** [comment]
Syncthing-bar registeres itself here:

/Library/LaunchAgents/koeln.mop.syncthing-bar.agent.plist

From http://launchd.info/:

Global Agents	/Library/LaunchAgents	Currently logged in user

I am confused :S Did I understand you correctly? It should run as the user who logged in:

hans-guenther:scripts mop$ ps aux | grep sync
mop               452   0,0  0,1 145247788  24308   ??  S     8:39am   0:01.79 /Applications/syncthing-bar.app/Contents/Resources/syncthing/syncthing

**Comment by m0ppers** [comment]
please reopen if you can provide more info or if this is still a problem
