### ISSUE TITLE
'Open UI' and 'Stop Syncthing' menu items grayed out

### ISSUE THREAD

**Issue by crahan** [m0ppers/syncthing-bar#21]
Hi, in the latest update (0.0.8) the 'Open UI' and 'Stop Syncthing' menu items are grayed out for me. Is there anything in particular that needs to be done to get those menu items working? Thanks!

Connecting to http://localhost:8084 brings up the Syncthing web interface, so the application is running in the background as it should.

![screen shot 2015-10-24 at 23 15 46](https://cloud.githubusercontent.com/assets/172588/10712821/3dbf9a20-7aa5-11e5-9fc5-cbbd9d049a5f.png)

**Comment by m0ppers** [comment]
Interesting :O This will happen if syncthing doesn't come up or if the port couldn't be determined. Any log output?

**Comment by crahan** [comment]
This is what the log shows:

OUT: [3KDS4] 10:12:57 INFO: syncthing v0.11.26 “Aluminium Ant” (go1.4.2 darwin-amd64 default) unknown-user@syncthing-builder 2015-10-02 06:08:07 UTC
OUT: [3KDS4] 10:12:57 INFO: My ID: <ID blanked out>
OUT: [3KDS4] 10:12:57 INFO: Database block cache capacity 65536 KiB
OUT: [3KDS4] 10:12:57 OK: Ready to synchronize default (read-write)
OUT: [3KDS4] 10:12:57 INFO: Starting web GUI on http://127.0.0.1:8084/
OUT: [3KDS4] 10:12:57 INFO: Completed initial scan (rw) of folder default
OUT: [3KDS4] 10:12:57 INFO: Starting local discovery announcements
OUT: [3KDS4] 10:12:57 INFO: Starting global discovery announcements
OUT: [3KDS4] 10:12:57 INFO: Device <ID blanked out> is “geodon” at [dynamic]
OUT: [3KDS4] 10:12:57 INFO: API listening on 127.0.0.1:8084

I've removed the device ID from the output. The web UI on http://localhost:8084 works fine too. I can add folders and change configuration settings.

**Comment by m0ppers** [comment]
Just to verify. If you reinstall 0.0.7 everything works fine?

**Comment by alyberty** [comment]
Maybe this is caused by AppTransport Security. ( https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/ )
It restricts an non TLS 1.2 connection. Because the default ssl certificate of syncthing is not signed it is refused.

**Comment by m0ppers** [comment]
@alyberty Thanks for the hint. That sounds very likely. By upgrading the Swift version I probably targeted   El Capitan as well. To get some more info:

@crahan Do you have El Captain? Can you quit syncthing-bar and launch it from the command line? That should get some more infos. I should really stream everything into the log :|

**Comment by crahan** [comment]
Hi @m0ppers, I am running El Capitan. Looks like @alyberty was right though. This is the output when I launch via the command line:

Syncthing version 0 11 26
2015-10-25 15:22:20.776 syncthing-bar[3666:352597] App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.

**Comment by crahan** [comment]
As a test, I've set NSAllowsArbitraryLoads to 'Yes' in the Info.plist file and now all menubar items show up as expected (including an entry for the folder that's configured).

**Comment by m0ppers** [comment]
Great! If possible could you try the following in your Info.plist?

I am still on yosemite and can't really test.

```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSExceptionDomains</key>
    <dict>
        <key>localhost</key>
        <dict>
            <key>NSExceptionAllowsInsecureHTTPLoads</key>
            <true/>
        </dict>
    </dict>
</dict>
```
AllowArbitraryLoads is the sledgehammer ;) The thing above should be sufficient.

If that works and if you want (for honor and glory!) you could send a pull request :O Otherwise I will simply change it later ;)

**Comment by crahan** [comment]
Took a stab at a pull request, but apparently the Github CI builds fails. If anything needs to be changed, definitely let me know as this is my first time contributing to an OS X app ;)

**Comment by m0ppers** [comment]
Thank you! One last (final, ultimate) question: Does the new release work for you? Then I will announce the new version.

https://github.com/m0ppers/syncthing-bar/releases/tag/0.0.9

**Comment by crahan** [comment]
Hi @m0ppers, I installed 0.0.9 and everything appears to be working as expected. Menubar items are active and start/stop syncthing works. Thanks!

**Comment by m0ppers** [comment]
:+1:
