### ISSUE TITLE
syncthing-bar closes itself when mac is hibernating

### ISSUE THREAD

**Issue by patbaumgartner** [m0ppers/syncthing-bar#23]
after a few hours, or when i close the lid of my mac, the syncthing-bar closes automatically. (I never saw it going down, but when I open my mac again, its gone)

**Comment by m0ppers** [comment]
hmmm..interesting...this doesn't happen on my mac. Can you provide more details about your system? When I originally build the bar I was on Yosemite and now I am on El Captain. I never experienced such a bug.

What OS are you using?

Can you start syncthing-bar on the command line and trigger that problem? Maybe that will give us a clue about what happened. Maybe some crash or so.

**Comment by patbaumgartner** [comment]
Actually I use 11.11 but got tonight a new update ... need to check if
makes a difference. but so far, entering the sleep mode multiple times,
synthing-bar is still working. Seems the issue is dissolved.
