### ISSUE TITLE
syncthing-bar exists with fatal error

### ISSUE THREAD

**Issue by CR0CKER** [m0ppers/syncthing-bar#24]
The app always exits with a fatal error, see error log below. Maybe cause by the fact that I had a separate synching installation before, which was the latest version? not sure. I've removed the standalone version of syncthing (didn't realize at first that it was bundled), but still the same. Rebooted, and did a clean reinstall of syncthing-bar, neither of which helped solve it.

OUT: [QEUDG] 17:00:32 INFO: synching v0.11.6 (go1.4.2 darwin-amd64 default) unknown-user@syncthing-builder 2015-05-23 23:58:46 UTC
OUT: [QEUDG] 17:00:32 INFO: My ID: XXX
OUT: [QEUDG] 17:00:32 INFO: Archiving a copy of old config file format
OUT: [QEUDG] 17:00:32 INFO: Database block cache capacity 65536 KiB
OUT: [QEUDG] 17:00:32 INFO: Starting web GUI on http://127.0.0.1:8084/
OUT: [QEUDG] 17:00:33 FATAL: Bad listen address: too many colons in address tcp://0.0.0.0:22000
OUT: [QEUDG] 17:00:33 INFO: synching v0.11.6 (go1.4.2 darwin-amd64 default) unknown-user@syncthing-builder 2015-05-23 23:58:46 UTC

**Comment by alyberty** [comment]
This rather looks like a problem with syncthing itself, rather then syncthing-bar.  The syncthing version in the logs isn't the latest. Maybe the standalone version was a newer version which updated the config ( config is located under ~/Library/Application Support/Syncthing ) and thus making it unreadable for the old version. Maybe delete/backup the config and retry. The Syncthing bundled should then be able to update itself.
I think the main problem is, that the bundled syncthing version is to old.
Or compile it manually and add the latest syncthing version.

**Comment by m0ppers** [comment]
hi...finally found some time to look into this. @alyberty seems to be right. Actually you seem to have hit this bug here https://github.com/syncthing/syncthing/issues/2325 . It seems you need to fix the config manually :S Can you verify?

**Comment by CR0CKER** [comment]
Yes, that fixed it: I renamed the old syncthing config, then installed syncthing-bar and let it upgrade, and then replaced the default config with my former one. Would be nice if synching-bar could detect this conflict and maybe automate? Or we ship syncthing-bar with the latest version instead of an older one to make sure it doesn't fail when reading existing configs?

**Comment by m0ppers** [comment]
Yeah I should probably just release a new version with an updated syncthing. Will do that somewhen next week :)

**Comment by m0ppers** [comment]
newer release is out. closing :)
