### ISSUE TITLE
0.0.11 crashes on 10.10.5

### ISSUE THREAD

**Issue by x0x01** [m0ppers/syncthing-bar#27]
```
Process:               syncthing-bar [593]
Path:                  /Applications/syncthing-bar.app/Contents/MacOS/syncthing-bar
Identifier:            koeln.mop.syncthing-bar
Version:               1.0 (1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           syncthing-bar [593]
User ID:               501

Date/Time:             2016-06-08 10:12:05.570 +0400
OS Version:            Mac OS X 10.10.5 (14F1808)
Report Version:        11
Anonymous UUID:        DBDFEC62-9B8C-C4A2-CD59-C548687D374F


Time Awake Since Boot: 1000 seconds

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000f4ac4bb7

VM Regions Near 0xf4ac4bb7:
--> 
    __TEXT                 0000000106548000-000000010656a000 [  136K] r-x/rwx SM=COW  /Applications/syncthing-bar.app/Contents/MacOS/syncthing-bar
```

**Comment by saesh** [comment]
Same here (OS X 10.11.5).

**Comment by m0ppers** [comment]
I guess something is AGAIN wrong with packaging. Will put a big warning onto the release. Will investigate in the evening. I am at work now :S If somebody can provide a full backtrace and/or trying to package it for themselves (scripts/make_release.sh 0.0.11) that would be helpful.

**Comment by saesh** [comment]
Sure. I packaged it and it runs fine without crashing.

[syncthing-bar-0.0.11.pkg.zip](https://github.com/m0ppers/syncthing-bar/files/304281/syncthing-bar-0.0.11.pkg.zip)

**Comment by m0ppers** [comment]
ok I repackaged again and for me it seems to work? Can somebody verify? I really need to figure out what is happening during packaging. This is the second time that happened :|

**Comment by x0x01** [comment]
it's alive! Works for me.

**Comment by saesh** [comment]
Works for me too!

**Comment by m0ppers** [comment]
great...thanks for the patience and testing! I will try to figure out what is going on in the release script until next time.
