### ISSUE TITLE
Feature Request: Ability to turn off auto-updates

### ISSUE THREAD

**Issue by mplorentz** [m0ppers/syncthing-bar#5]
I'd love to use syncthing-bar but unfortunately it auto-updates itself on startup. I have Syncthing installed on multiple computers so this causes my setup to be running multiple versions of Syncthing.

A preference that allowed me to turn off auto-updating would solve this problem.

**Comment by mplorentz** [comment]
So I just saw that Syncthing now has it's own checkbox for automatic upgrades on the settings page. Does syncthing-bar rely on this automatic upgrade mechanism? If so it looks like I could turn it off there.

**Comment by m0ppers** [comment]
no. absolutely not....i just thought "ok its updating itself anyway. so lets do it beforehand". i will remove it later (lacking time currently). maybe as a quick fix you might simply do a chmod -w on the bundled syncthing

**Comment by m0ppers** [comment]
i removed the auto upgrade stuff and packaged a new release :)

**Comment by mplorentz** [comment]
Thanks!
