### ISSUE TITLE
Feature request: support 10.7.5 Lion

### ISSUE THREAD

**Issue by dreamcat4** [m0ppers/syncthing-bar#6]
Feature request: support 10.7.5 Lion

Sorry. Can't run newer versions of OS X on MacMini 1,1 hardware.

**Comment by m0ppers** [comment]
hi...sorry but i am not going to fix this one :( the bar was a weekend experiment and the recent version of xcode creates a project which only works in yosemite. I would have to dive deep into cocoa to find out a good way (which won't immediately break with a new os-x version) to fix that. However if someone is willing to provide a patch i would gladly accept :) leaving it open so far

**Comment by dreamcat4** [comment]
Ok thanks. Please leave open. In meantime I have a basic scripted solution which uses xMenu.app.

**Comment by dreamcat4** [comment]
Ok thanks. Please leave open. In meantime I have a basic scripted solution which uses xMenu.app.

**Comment by cmroanirgo** [comment]
I also agree with a need to run on older OSX. You can get older versions of xcode from apple: http://developer.apple.com/downloads. With that you can develop and test (on yosemite) using a build that should be ok for older systems. 
(PS: I suspect you'll forever get this style of request while you have this code on github ;)  )

**Comment by chrisidefix** [comment]
@dreamcat4 why should this issue remain open, if nobody is going to fix it ?

**Comment by chrisidefix** [comment]
@cmroanirgo you do not need an old Xcode version to compile code that can run on former versions of the OS. All you need is the appropriate SDK and set the correct **Deployment Target** in Xcode.

However, for this project, unless someone decides to rewrite it in Objective-C, you *CAN NOT* do this. This project was written in *Swift*, which can only be deployed to OS X versions 10.9 and up (see stackoverflow discussion below or official release notes).

http://stackoverflow.com/questions/24001778/do-swift-based-applications-work-on-os-x-10-9-ios-7-and-lower

**Comment by dreamcat4** [comment]
@chrisidefix Thanks for pointing that out in regards to the swift. It's been left open due to the sentiments and agreement of the repo owner @m0ppers, which we appreciate:

> However if someone is willing to provide a patch i would gladly accept :) leaving it open so far

And I doubt any project written in 1 weekend cannot be entirely re-written in Obj-C in a roughly similar timeframe. And sure - that would be not so much a patch as an entire re-write. Yet there is still a value that we might comment here later on where to find a suitable alternative.

**Comment by chrisidefix** [comment]
@dreamcat4 Alright, I see your point :bow: However, an **open** issue makes people assume that this very well might be fixed in the future, which in my opinion is highly unlikely, as this project was more or less a learning experience for @m0ppers to see what *Swift* can do - rewriting this in *Objective-C* doesn't seem reasonable under such circumstances .

Also, closing the issue doesn't make the thread disappear, it just moves it to *Closed Issues*, so we could still add comments and such later on.

Regarding alternatives, I can recommend https://github.com/jaredks/rumps which is a super simple framework for designing os x menu bar applications - in less than a weekend :wink:

**Comment by m0ppers** [comment]
i was and am a total rookie concerning swift and cocoa development. as @chrisidefix pointed out this thing here is written in swift. I was not aware that it is impossible to deploy a swift app to Lion. It seems (http://stackoverflow.com/questions/24001778/do-swift-based-applications-work-on-os-x-10-9-ios-7-and-lower) Mavericks is the bare minimum to launch swift applications. So yes: This would be a complete rewrite and won't happen. Sorry :(
