### ISSUE TITLE
Enhancement: Use REST interface to display useful information

### ISSUE THREAD

**Issue by DanTheColoradan** [m0ppers/syncthing-bar#7]
https://github.com/syncthing/syncthing/wiki/REST-Interface

What do you think? I haven't looked yet, but I was thinking of giving it a go in swift. I haven't used swift at all though :)

**Comment by m0ppers** [comment]
Yeah i am already using that to determine the folders :)

See https://github.com/m0ppers/syncthing-bar/blob/master/syncthing-bar/SyncthingRunner.swift#L125

The question is what is useful information :)

**Comment by DanTheColoradan** [comment]
Haha good point! How about [system](https://github.com/syncthing/syncthing/wiki/REST-Interface#get-restsystem) to start?

I'm also considering these if I'm successful:

- [device id (with mouse click to copy?)](https://github.com/syncthing/syncthing/wiki/REST-Interface#get-restdeviceid)
- [connections](https://github.com/syncthing/syncthing/wiki/REST-Interface#get-restconnections)
- [sync (i.e. status?)](https://github.com/syncthing/syncthing/wiki/REST-Interface#get-restconfigsync)

**Comment by m0ppers** [comment]
I would suggest a (disabled) menu bar item which shows some general information. Detailed information could be retrieved upon clicking a second menu bar item.

What would be important to me: statistics etc will only be collected upon opening the menu. I want syncthing-bar to be as lightweight as possible. Currently the folders are updated every 10 seconds regardless of wether you need it or not. I consider this a bug (and i am personally to blame for that :D). I was simply to lazy to fix it (yet) ;)

Does that make sense to you?

**Comment by DanTheColoradan** [comment]
It does indeed. 

I still need to wrap my head around swift so I'm going to do some light reading and playing with it this weekend. It should be fun :D

**Comment by m0ppers** [comment]
looking forward to the results :D

**Comment by DanTheColoradan** [comment]
Didn't get far enough yet! I was occupied a bit with my new pup and YubiKey. Learning some swift now.

**Comment by m0ppers** [comment]
:dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog:

**Comment by DanTheColoradan** [comment]
Lol Mac Mail couldn't render that much cuteness!

![screen shot 2015-03-30 at 3 11 22 pm](https://cloud.githubusercontent.com/assets/3826143/6906927/1c168a82-d6ef-11e4-88da-25a6e8c141e2.png)

**Comment by m0ppers** [comment]
:bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug:

**Comment by DanTheColoradan** [comment]
Lol that one caused the same problem.

Going to close this until I have more time to work on it. Reopen it if you want :)

**Comment by chrisidefix** [comment]
Just saw this - probably similar to my new issue #10
