### ISSUE TITLE
Enhancement: Use existing / running syncthing and avoid bundle.

### ISSUE THREAD

**Issue by chrisidefix** [m0ppers/syncthing-bar#9]
I haven't looked at how `syncthing-bar` works exactly, but it looks like it is starting / running `syncthing` from an internal folder. I would like to improve this and instead make the location **configurable** or - *even better* - **not** start `syncthing` at all and make `syncthing-bar` independent.

When starting `syncthing-bar` it should first check if an instance of `syncthing` is already running - most likely at `127.0.0.1:8080`. This way I could for example use this handy [`.app` wrapper](https://github.com/syncthing/syncthing-mac) to run syncthing, but also use your menubar.

Let me know if you think this doesn't really make sense to you.

**Comment by m0ppers** [comment]
the idea of syncthing bar is to make it as simple as possible. i am old and lazy so i don't care about versions and i don't want to configure it. It should "just work". This is one of the fundamental ideas of this project. Sorry. This won't happen (feel free to fork though). Debundling syncthing needs a lot of configuring: ports, api keys etc. it is just not worth it (for me). from both points of view: developer AND user

**Comment by chrisidefix** [comment]
Yeah, I guess you are right - in the end it's probably easier for the average user this way.
